apiVersion: v1
kind: Secret
metadata:
  name: authz-env-secret
  namespace: google-authz
type: Opaque
stringData:
  APP_ENV: production
  APP_VERSION: 0.2.0
  SAMPLE_USER_EMAIL: sample.user@example.com
  GOOGLE_SERVICE_ACCOUNT_FILE: /etc/credentials.json
  GOOGLE_WORKSPACE_DELEGATED_USER: delegated-admin@example.com
  GOOGLE_WORKSPACE_CUSTOMER_ID: YOUR_CUSTOMER_ID
  GOOGLE_WORKSPACE_AUTH_SCHEMA: Authorization
  WORKSPACE_REQUEST_TIMEOUT: "30"
